### PR TITLE
GeneralMidi2Percussion-Map

### PR DESCRIPTION
**Pull request by FischertBilligheim**
I added a GeneralMidi2Percussion-Map.

### CODE REVIEW

**Comment by FischertBilligheim** [comment]
Sorry, I did not want to change the „Playback.cs“. 
Forking, branching and pull requests is a new topic for me...

**Comment by FischertBilligheim** [comment]
I also assume, that the compiler-project file must be changed - the new cs file must be adapted....? I will have a Look to that this evening ...

**Comment by melanchall** [comment]
> I also assume, that the compiler-project file must be changed - the new cs file must be adapted....?

No, it looks good :) I'll merge as soon as all checks passed. I've started failed build rerun.

**Comment by melanchall** [comment]
Merged. Thanks Thomas!

**Pull request merged**
