### PR TITLE
Added .NET 6 support

### PR DESCRIPTION
**Pull request by mbwilding**
As the title says.

### CODE REVIEW

**Comment by melanchall** [comment]
@mbwilding Thanks for PR! But the library already targets .NET Standard 2.0. .NET 6 implements .NET Standard so there is no reason to target net6.0 explicitly.

**Comment by mbwilding** [comment]
It doesn't work in a .NET 6 app as a referenced project, I had to fork and do that small edit and it works now.

**Comment by melanchall** [comment]
Hmm, very interesting. Can you please answer a couple of questions?

1. Why do you need to use the library via referencing its csproj and not via NuGet package?
2. Can you please show what error you get?

Your change is small and easy but following your logic I need to add many other TFMs in csproj. And that looks strange since .NET Standard already covers different cases. So I need to take right decision.

**Comment by mbwilding** [comment]
> Hmm, very interesting. Can you please answer a couple of questions?
> 
> 1. Why do you need to use the library via referencing its csproj and not via NuGet package?
> 2. Can you please show what error you get?
> 
> Your change is small and easy but following your logic I need to add many other TFMs in csproj. And that looks strange since .NET Standard already covers different cases. So I need to take right decision.

**Comment by mbwilding** [comment]
Showing in both Rider and VS2022. This is using the Nuget package. Doesn't work with a .NET 6 project.

Here is a link to the project if you want to try it yourself, it's using a forked branch with that .NET 6 edit in the csproj to work currently.

RIDER
VS2022

**Comment by mbwilding** [comment]
> What if you
> 
> 1. Close VS
> 2. Delete bin/obj folders in the project directory
> 3. Open VS
> 4. Click Restore NuGet packages on solution
> 
> ? Please use NuGet package of the DryWetMIDI. It must work in NET 6 without any problems. And it works, I've tried.
> 
> Also what if you create empty solution with two projects: one on NET Standard and one on NET 6? And last one references first one.

That fixed it! I feel like an idiot. Sorry for wasting your time and making you reply to me. Closing the ticket.

**Pull request closed without merging**
